### ISSUE TITLE
Declare compatibility with the 'High-Performance order storage' feature.

### ISSUE THREAD

**Issue by aniaq** [helgatheviking/add-to-cart-form-shortcode#13]
When I try to activate the plugin, I get error "WooCommerce has detected that some of your active plugins are incompatible with currently enabled WooCommerce features. Please  review the details - (/wp-admin/plugins.php?plugin_status=incompatible_with_feature.

**Comment by helgatheviking** [comment]
Woo is way over aggressive about this... Which I guess is better than the alternative. 

Support is pretty straightforward to declare though. Open to PRs otherwise it'll have to wait until I get some time.

But this plugin has nothing to do with orders and therefore nothing to book with HPOS so it should be fine.
